"""Provide classes and functions for kernel computations in JAX."""

from nlsa.kernels import (
    ConePars as ConePars,
    KernelEigenbasis as KernelEigenbasis,
    make_bandwidth_rbf as make_bandwidth_rbf,
    make_kernel_family as make_kernel_family,
    make_integral_operator as make_integral_operator,
    left_normalize as left_normalize,
    right_normalize as right_normalize,
    sym_normalize as sym_normalize,
    right_sqrt_normalize as right_sqrt_normalize,
    sym_sqrt_normalize as sym_sqrt_normalize,
    dm_normalize as dm_normalize,
    dmsym_normalize as dmsym_normalize,
    from_dmsym as from_dmsym,
    bs_normalize as bs_normalize,
    bssym_normalize as bssym_normalize,
    compose as compose,
    make_mercer_kernel as make_mercer_kernel,
    riemannian_vol as riemannian_vol,
    bandwidth_normalization as bandwidth_normalization,
    make_bandwidth_function as make_bandwidth_function,
    make_scaled_sqdist as make_scaled_sqdist,
    make_tuning_objective as make_tuning_objective,
    make_resolvent_compactification_kernels as make_resolvent_compactification_kernels,
)
from nlsa.jax.kernels._kernels import (
    TunePars as TunePars,
    TuneInfo as TuneInfo,
    DmKernelPars as DmKernelPars,
    BsKernelPars as BsKernelPars,
    KernelPars as KernelPars,
    KernelEigen as KernelEigen,
    KernelEigenShardings as KernelEigenShardings,
    tune_bandwidth as tune_bandwidth,
    tune_bandwidth_from_shape_function as tune_bandwidth_from_shape_function,
    compute_eigen_dm as compute_eigen_dm,
    compute_eigen_bs as compute_eigen_bs,
    compute_eigen as compute_eigen,
    make_eigenvector_extension as make_eigenvector_extension,
    make_eigenbasis_operators as make_eigenbasis_operators,
    make_eigenbasis_dm as make_eigenbasis_dm,
    make_eigenbasis_bs as make_eigenbasis_bs,
    make_eigenbasis as make_eigenbasis,
    plot_kernel_tuning as plot_kernel_tuning,
    plot_laplace_spectrum as plot_laplace_spectrum,
    to_laplace_eigenvalues as to_laplace_eigenvalues,
    to_kernel_eigen as to_kernel_eigen,
)
