"""Provide classes and functions for kernel computations in JAX."""

from nlsa.kernels import (
    BsKernelPars as BsKernelPars,
    ConePars as ConePars,
    DmKernelPars as DmKernelPars,
    KernelEigen as KernelEigen,
    KernelEigenbasis as KernelEigenbasis,
    KernelPars as KernelPars,
    TuneInfo as TuneInfo,
    TunePars as TunePars,
    bs_normalize as bs_normalize,
    bssym_normalize as bssym_normalize,
    compose as compose,
    dm_normalize as dm_normalize,
    dmsym_normalize as dmsym_normalize,
    from_dmsym as from_dmsym,
    kernel_vol as kernel_vol,
    left_normalize as left_normalize,
    make_integral_operator as make_integral_operator,
    make_mercer_kernel as make_mercer_kernel,
    make_rbf as make_rbf,
    make_rbf_kernel_family as make_rbf_kernel_family,
    make_resolvent_compactification_kernels as make_resolvent_compactification_kernels,
    make_scaled_sqdist as make_scaled_sqdist,
    make_tuning_objective_from_kernel_family as make_tuning_objective_from_kernel_family,
    plot_kaf_response_coeffs as plot_kaf_response_coeffs,
    plot_kernel_tuning as plot_kernel_tuning,
    riemannian_vol as riemannian_vol,
    right_normalize as right_normalize,
    right_sqrt_normalize as right_sqrt_normalize,
    sym_normalize as sym_normalize,
    sym_sqrt_normalize as sym_sqrt_normalize,
)
from nlsa.jax.kernels._kernels import (
    KernelEigenShardings as KernelEigenShardings,
    compute_eigen as compute_eigen,
    compute_iterative_kaf_preds as compute_iterative_kaf_preds,
    compute_kaf_preds as compute_kaf_preds,
    make_bandwidth_tuner as make_bandwidth_tuner,
    make_bs_eigensolver as make_bs_eigensolver,
    make_data_driven_bandwidth_function as make_data_driven_bandwidth_function,
    make_data_driven_bs_kernel_op as make_data_driven_bs_kernel_op,
    make_data_driven_dm_kernel_op as make_data_driven_dm_kernel_op,
    make_data_driven_eigenbasis as make_data_driven_eigenbasis,
    make_data_driven_rbf_kernel as make_data_driven_rbf_kernel,
    make_data_driven_scaled_sqdist as make_data_driven_scaled_sqdist,
    make_dm_eigensolver as make_dm_eigensolver,
    make_eigenbasis as make_eigenbasis,
    make_eigenbasis_bs as make_eigenbasis_bs,
    make_eigenbasis_dm as make_eigenbasis_dm,
    make_eigenbasis_operators as make_eigenbasis_operators,
    make_eigensolver as make_eigensolver,
    make_eigenvector_extension as make_eigenvector_extension,
    make_eigh_dm_eigensolver as make_eigh_dm_eigensolver,
    make_eigsh_dm_eigensolver as make_eigsh_dm_eigensolver,
    make_iterative_kaf_analysis_operator as make_iterative_kaf_analysis_operator,
    make_kaf_analysis_operator as make_kaf_analysis_operator,
    make_kaf_prediction_function as make_kaf_prediction_function,
    make_svd_bs_eigensolver as make_svd_bs_eigensolver,
    make_svds_bs_eigensolver as make_svds_bs_eigensolver,
    plot_laplace_spectrum as plot_laplace_spectrum,
    slice_eigen as slice_eigen,
    to_laplace_eigenvalues as to_laplace_eigenvalues,
    tune_bandwidth as tune_bandwidth,
)
