function tag = getDefaultTag(obj)
% GETDEFAULTTAG  Get default tag of nlsaDiffusionOperator_gl_mb_ps_pf objects.
%
% Modified 2023/07/31

l = getBandwidthExponentLimit(obj);
tag = sprintf('alpha%1.2f_eps%1.2g_b%1.2g_lLim%1.2g-%1.2g_nL%i_bs_pf_nPhi%i', ...
              getAlpha(obj), ...
              getEpsilon(obj), ...
              getBandwidthBase(obj), ...
              l(1), l(2), ...
              getNBandwidth(obj), ...
              getNEigenfunction(obj));
